# Description: IntelliJ protobuf plugin - Go language support.
#

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:private"])

alias(
    name = "golang",
    actual = "//golang/src/main:golang",
    visibility = ["//visibility:public"],
)

alias(
    name = "optional_plugin_xml",
    actual = "//golang/src/main:optional_plugin_xml",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_library",
    actual = "//golang/src/main:plugin_library",
    visibility = ["//:plugin_private"],
)
