# Description: IntelliJ protobuf plugin - erlang language support.
#

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:private"])

alias(
    name = "erlang",
    actual = "//erlang/src/main:erlang",
    visibility = ["//visibility:public"],
)

alias(
    name = "optional_plugin_xml",
    actual = "//erlang/src/main:optional_plugin_xml",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_library",
    actual = "//erlang/src/main:plugin_library",
    visibility = ["//:plugin"],
)
