# Description: IntelliJ protobuf plugin - core.
#

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:private"])

alias(
    name = "core",
    actual = "//core/src/main:core",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_for_tests",
    actual = "//core/src/main:plugin_for_tests",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_xml",
    actual = "//core/src/main:plugin_xml",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_library",
    actual = "//core/src/main:plugin_library",
    visibility = ["//:plugin_private"],
)
