# Description: IntelliJ protobuf plugin - Java language support.
#

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:private"])

alias(
    name = "java",
    actual = "//java/src/main:java",
    visibility = ["//visibility:public"],
)

alias(
    name = "optional_plugin_xml",
    actual = "//java/src/main:optional_plugin_xml",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_library",
    actual = "//java/src/main:plugin_library",
    visibility = ["//:plugin"],
)
