# Description: IntelliJ protobuf plugin - Python language support.
#

licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:private"])

alias(
    name = "python",
    actual = "//python/src/main:python",
    visibility = ["//visibility:public"],
)

alias(
    name = "optional_plugin_xml",
    actual = "//python/src/main:optional_plugin_xml",
    visibility = ["//visibility:public"],
)

alias(
    name = "plugin_library",
    actual = "//python/src/main:plugin_library",
    visibility = ["//:plugin_private"],
)
